### ISSUE TITLE
CI: Cache test artifact 

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/sorock#361]
The bottleneck in CI is the last part: `cargo test`

```yaml
      - name: Run tests
        run: |
          docker compose -f docker-compose.ci.yml build
          docker compose -f docker-compose.ci.yml run --rm dev cargo test
```

This will execute everything from scratch because nothing is cached. How can I cache it?
